Comparing and Sorting: Additions and reordering
frenzymadness/portingguide pull request #1
Opened 2016-09-16 14:22 UTC by encukou

I started doing some light edits, but then it grew into rewriting a lot more that I originally wanted. Sorry for that; next time I'll try to do more interaction on the pull request.

2016-09-19 09:37 UTC, frenzymadness commented on source/comparisons.rst
> +    ...     """Key for comparison that returns a reversed string"""
Forgotten comment change

2016-09-19 09:39 UTC, frenzymadness commented on source/comparisons.rst
> +However, discovering it is straightforward: the call ing ``sort`` with the
Extra space in "call ing"

2016-09-19 09:44 UTC, frenzymadness requested changes
Just two small changes are needed.

Thank you for your work. Unfortunately, almost all my content is gone :( so I will try to do a better job next time.

2016-09-21 12:39 UTC, encukou commented on source/comparisons.rst
> +    ...     """Key for comparison that returns a reversed string"""
Fixed & rebased

2016-09-21 12:39 UTC, encukou commented on source/comparisons.rst
> +However, discovering it is straightforward: the call ing ``sort`` with the
Fixed & rebased

2016-09-21 13:17 UTC, frenzymadness approved these changes

2016-09-21 13:17 UTC, merged